### ISSUE TITLE
iOS permissions to access gallery

### ISSUE THREAD

**Issue by Deadranight** [synecx/KikCam#1]
Hi there, I recently download your app. 
I met an issue at the beginning, it asks the permission for push notifications. But it doesn’t ask for the gallery pic so I can’t access to it from the app, which is pretty annoying. I’m in iOS 12.1 and I already reset confidentiality settings.

**Comment by ayotreezzy** [comment]
Im having the same problem

**Comment by pineappleberryfruit** [comment]
I’m having the same problem as well. I’m on IOS 12.1

**Comment by pineappleberryfruit** [comment]
also I downloaded your app from app valley and tweakbox. both say I don’t have permission to access my photos no matter what I do.

**Comment by rumo20** [comment]
Same issue too

**Comment by synecx** [comment]
This is an issue with iOS 12, rather than the tweak itself. I am closing this issue, but thanks for reporting it!

**Comment by davidrecham** [comment]
Hi there, have you got any news about this issue? Can’t you do anything to solve it?

**Comment by pineappleberryfruit** [comment]
no I haven’t
